#!/usr/bin/env python3
"""
gen_device_crypto.py — generate device_crypto.inc for gpu_scan.cu.

Mechanically transforms the vendored Monero sources (crypto-ops.h,
crypto-ops-data.c, crypto-ops.c, keccak.c's keccakf) into CUDA device code
by prefixing `__device__` to top-level functions and data. NO math is
touched: every non-blank emitted line is either an unmodified source line
or an unmodified source line with a `__device__ ` prefix.

Run: python3 gen_device_crypto.py  -> writes device_crypto.inc
"""
import re, sys

FUNC_DEF = re.compile(
    r'^(static\s+)?(void|int|unsigned\s+char|uint64_t|uint32_t|int64_t|int32_t)'
    r'\s+[a-zA-Z_][a-zA-Z0-9_]*\s*\(')
DATA_DEF = re.compile(r'^(static\s+)?const\s')

def transform_code(path, out):
    out.append(f'/* ===== generated from {path} ===== */')
    for line in open(path):
        line = line.rstrip('\n')
        if line.startswith('#include'):
            continue                      # single-TU include, headers handled here
        if FUNC_DEF.match(line) or DATA_DEF.match(line):
            out.append('__device__ ' + line)
        else:
            out.append(line)

def transform_header(path, out):
    out.append(f'/* ===== generated from {path} (decls) ===== */')
    for line in open(path):
        line = line.rstrip('\n')
        if line.startswith('#include') or line.startswith('#pragma'):
            continue
        if re.match(r'^extern\s+const\s', line):
            continue   # data defs (crypto-ops-data.c) precede use in this TU
        elif FUNC_DEF.match(line):
            out.append('__device__ ' + line)
        else:
            out.append(line)

def extract_keccakf(path, out):
    """keccakf + its round-constant table, verbatim with __device__."""
    src = open(path).read().split('\n')
    out.append(f'/* ===== generated from {path} (keccakf only) ===== */')
    emit = False
    for i, line in enumerate(src):
        if line.startswith('const uint64_t keccakf_rndc[24]'):
            emit = True
            out.append('__device__ ' + line)
            continue
        if line.startswith('void keccakf('):
            out.append('__device__ ' + line)
            continue
        if emit and line.startswith('// compute a keccak hash'):
            break
        if emit:
            out.append(line)

out = [
    '/* AUTO-GENERATED by gen_device_crypto.py — DO NOT EDIT.',
    ' * Source files are the vendored, unmodified Monero ref10 + keccak.',
    ' */',
    '#include <stdint.h>',
    '#ifndef assert',
    '#define assert(x) ((void)0)',
    '#endif',
    '#include "warnings.h"   /* no-op warning macros used by crypto-ops.c */',
    '#define ROTL64(x, y) (((x) << (y)) | ((x) >> (64 - (y))))',
    '#define KECCAK_ROUNDS 24',
    '#define select crypto_ops_ge_select   /* same rename as scan_cpu.c */',
]
transform_header('crypto-ops.h', out)
transform_code('crypto-ops-data.c', out)
transform_code('crypto-ops.c', out)
extract_keccakf('keccak.c', out)
out.append('#undef select')

with open('device_crypto.inc', 'w') as f:
    f.write('\n'.join(out) + '\n')
print(f'device_crypto.inc: {len(out)} lines')
